development:
  amadeus_client_id:
  amadeus_client_secret:
  nytimes_api_key:
  DB_FILENAME:
  SESSION_SECRET:

test:
  amadeus_client_id: 
  amadeus_client_secret: 
  nytimes_api_key: 
  DB_FILENAME: 
  SESSION_SECRET:

production:
  amadeus_client_id: 
  amadeus_client_secret: 
  nytimes_api_key: 
  DB_FILENAME: 
  SESSION_SECRET: